In [ ]:
from transformers import BertTokenizer, BertForMaskedLM
import torch

# Load pre-trained model and tokenizer
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertForMaskedLM.from_pretrained('bert-base-uncased')

# Move model to GPU if available
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model.to(device)


/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`


model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForMaskedLM: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight', 'cls.seq_relationship.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


BertForMaskedLM(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0-11): 12 x BertLayer(
          (attention): BertAttention(
            (self): BertSdpaSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12, elementwi

In [ ]:
#verb tense probing
sentences_tense = [
    "I walked to the store.",      # Past tense
    "I walk to the store.",       # Present tense
    "I will walk to the store."   # Future tense
]

# Tokenize sentences
inputs = tokenizer(sentences_tense, return_tensors='pt', padding=True, truncation=True).to(device)

# Pass through BERT model to get predictions
with torch.no_grad():
    outputs = model(**inputs)

# Print model outputs (logits for prediction analysis)
print(outputs.logits)


tensor([[[ -7.8719,  -7.7918,  -7.8209,  ...,  -7.0160,  -7.1298,  -4.6460],
         [-13.0280, -12.9212, -13.0315,  ..., -11.7415, -10.4555, -10.4250],
         [-10.8932, -10.6829, -10.8890,  ...,  -7.4729,  -8.7219,  -8.7599],
         ...,
         [-11.2085, -10.8364, -11.4187,  ...,  -8.8475, -10.9073,  -4.8946],
         [-12.6675, -12.8743, -12.6960,  ..., -10.3213,  -9.7448, -12.8511],
         [ -5.1986,  -5.0427,  -5.2584,  ...,  -5.4336,  -5.7707,  -4.2043]],

        [[ -8.5498,  -8.4769,  -8.5185,  ...,  -7.7313,  -7.8692,  -5.1287],
         [-16.4000, -15.9687, -16.3603,  ..., -13.6970, -13.8508, -13.1949],
         [-14.6868, -14.4856, -14.7752,  ..., -11.0767, -13.3555, -12.4930],
         ...,
         [-12.4200, -12.0421, -12.7345,  ...,  -9.1442, -11.8522,  -5.9846],
         [-13.4640, -13.5633, -13.6270,  ..., -10.8788, -11.2475, -12.9631],
         [ -5.6605,  -5.4883,  -5.8776,  ...,  -5.2129,  -6.2330,  -4.9046]],

        [[ -8.4187,  -8.3779,  -8.3835,  ...

In [ ]:
#Gender pronoun probing
sentences_pronouns = [
    "The doctor said he would arrive soon.",  # He (male pronoun)
    "The doctor said she would arrive soon."  # She (female pronoun)
]

# Tokenize sentences
inputs = tokenizer(sentences_pronouns, return_tensors='pt', padding=True, truncation=True).to(device)

# Pass through BERT model
with torch.no_grad():
    outputs = model(**inputs)

# Print model outputs (logits for prediction analysis)
print(outputs.logits)


tensor([[[ -7.2397,  -7.2350,  -7.1782,  ...,  -6.5750,  -6.3953,  -4.3009],
         [-11.3160, -11.1487, -11.1438,  ...,  -9.8288,  -9.6220,  -7.8080],
         [-11.2792, -11.6211, -11.4343,  ...,  -8.9830,  -8.5868,  -8.8019],
         ...,
         [-12.9843, -13.3019, -13.0186,  ..., -11.4304, -12.7524, -10.3688],
         [-12.8282, -12.6634, -12.6938,  ...,  -9.6188, -10.6063,  -7.9010],
         [-13.9510, -14.3085, -14.0468,  ..., -12.4832, -13.0409, -10.5589]],

        [[ -7.2771,  -7.2683,  -7.2272,  ...,  -6.5473,  -6.4377,  -4.2568],
         [-11.2270, -11.0559, -11.0821,  ...,  -9.7577,  -9.5589,  -7.4461],
         [-11.5374, -11.8683, -11.7577,  ...,  -9.4254,  -8.6497,  -8.3848],
         ...,
         [-12.5113, -12.8266, -12.5420,  ..., -11.1191, -12.3359,  -9.5022],
         [-12.6096, -12.3933, -12.4390,  ...,  -9.6272, -10.5561,  -7.4523],
         [-11.5559, -12.0038, -11.6295,  ..., -10.0701, -10.4004,  -8.7562]]])


In [ ]:
#World Knowledge probing
sentences_world_knowledge = [
    "The capital of France is Paris.",    # Factual sentence
    "The capital of France is Berlin."   # Factual mistake
]

# Tokenize sentences
inputs = tokenizer(sentences_world_knowledge, return_tensors='pt', padding=True, truncation=True).to(device)

# Pass through BERT model
with torch.no_grad():
    outputs = model(**inputs)

# Print model outputs (logits for prediction analysis)
print(outputs.logits)


tensor([[[ -7.1140,  -7.0738,  -7.0593,  ...,  -6.2999,  -6.3294,  -4.2466],
         [-12.1902, -12.3267, -12.2044,  ..., -10.4680, -10.0508, -10.2791],
         [-10.4527, -10.9599, -10.5319,  ...,  -8.1483,  -7.0937, -12.3911],
         ...,
         [-10.4106, -10.7325, -10.7013,  ...,  -8.2587,  -8.8822,  -8.7654],
         [-10.8909, -10.7947, -11.0098,  ...,  -9.6976, -10.0613,  -5.8069],
         [-11.8922, -12.2394, -12.0421,  ..., -11.2835, -12.2560,  -8.7891]],

        [[ -7.2335,  -7.2171,  -7.1736,  ...,  -6.3629,  -6.4291,  -4.4505],
         [-14.0927, -14.4775, -14.0633,  ..., -12.2849, -11.2113, -12.6615],
         [-10.5590, -11.1076, -10.4244,  ...,  -8.2543,  -7.1135, -11.8844],
         ...,
         [-10.3681, -10.5680, -10.0458,  ...,  -9.0316, -10.0583,  -8.3993],
         [-12.1723, -12.0774, -12.2141,  ..., -10.2595, -11.5270,  -4.7196],
         [-11.6958, -11.9579, -11.6571,  ..., -10.4037, -12.1671,  -6.1732]]])


In [ ]:
import torch.nn.functional as F

# Example of extracting probabilities from logits for the first sentence in the world knowledge test
probabilities = F.softmax(outputs.logits, dim=-1)

# Print probabilities for a specific token (for example, checking 'Paris' vs 'Berlin' for world knowledge)
print(probabilities[0, 0, tokenizer.encode("Paris", add_special_tokens=False)[0]].item())
print(probabilities[0, 1, tokenizer.encode("Berlin", add_special_tokens=False)[0]].item())


0.00021864693553652614
1.9658382655052264e-07


#Layer-wise Explainability of BERT

In [ ]:
pip install captum

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 4.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 31.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.3/18.3 MB 91.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 1.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 47.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 38.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 49.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 2.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 5.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 13.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 7.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 6.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21

In [ ]:
import torch
from transformers import BertTokenizer, BertForSequenceClassification
from captum.attr import LayerIntegratedGradients

In [ ]:
model_name= "bert-base-uncased"
tokenizer=BertTokenizer.from_pretrained(model_name)
model=BertForSequenceClassification.from_pretrained(model_name)
model.eval()
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`


model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


BertForSequenceClassification(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0-11): 12 x BertLayer(
          (attention): BertAttention(
            (self): BertSdpaSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e

In [ ]:
sentence ="I absolutely loved the movie!"
inputs = tokenizer(sentence, return_tensors='pt', truncation=True).to(device)

In [ ]:
#helper fuunction for captum
def predict(inputs):
    outputs = model(**inputs)
    return torch.softmax(outputs.logits, dim=-1)

def forward_func(input_embeds):
    attention_mask = torch.ones(input_embeds.size()[:-1]).to(device)
    output = model(inputs_embeds=input_embeds, attention_mask=attention_mask)
    return torch.softmax(output.logits, dim=-1)

# Choose a target label (0 or 1) for explanation
target_label = 1  # Suppose 1 = Positive Sentiment


In [ ]:
# Initialize Layer Integrated Gradients
lig = LayerIntegratedGradients(forward_func, model.bert.embeddings)

# Get input embeddings
input_ids = inputs["input_ids"]
embeddings = model.bert.embeddings(input_ids)

# Compute Layer-wise attributions
attributions, delta = lig.attribute(inputs=embeddings,
                                    baselines=torch.zeros_like(embeddings),
                                    target=target_label,
                                    return_convergence_delta=True)

# Summing over the embedding dimension
layer_attributions = attributions.sum(dim=-1).squeeze(0).detach().cpu()

# Visualize
print(layer_attributions)


tensor([ 7.0583e-03,  1.8908e-03,  1.0849e-02,  6.2166e-03,  1.1716e-03,
         6.1811e-03, -5.1659e-05,  1.2122e-01])


In [ ]:
def layer_forward_func(hidden_states):
    attention_mask = torch.ones(hidden_states.size()[:-1]).to(device)
    output = model(inputs_embeds=hidden_states, attention_mask=attention_mask)
    return torch.softmax(output.logits, dim=-1)

# Now, pick a layer
layer_module = model.bert.encoder.layer[8].output

# Layer Integrated Gradients for layer 8
lig = LayerIntegratedGradients(layer_forward_func, layer_module)

# Attribution for that layer
attributions, delta = lig.attribute(inputs=embeddings,
                                    baselines=torch.zeros_like(embeddings),
                                    target=target_label,
                                    return_convergence_delta=True)

# Sum across tokens and dimensions
layer_score = attributions.sum().item()
print(f"Layer 8 Attribution Score: {layer_score}")


Layer 8 Attribution Score: 0.034893691539764404
